bitcoindevkit/bdk-cli

README.md
src/lib.rs
src/repl.rs

This issue fixes #1 by removing the `--log_level` option which was overriding the `RUST_LOG` environment variable but does not provide the same level of logging control.
Also in this PR I added a couple more usage examples in the README, including an example for using the `RUST_LOG` env variable.

Remove log level

---

.github/pull_request_template.md
.github/workflows/audit.yml
.github/workflows/code_coverage.yml
.github/workflows/cont_integration.yml
README.md
src/lib.rs

This PR fixes tests broken in #2 and adds Github Actions workflows to build, test and check code formating; and generate test code coverage report.

Add GitHub CI and Code Coverage workflows

---

CHANGELOG.md
src/lib.rs
src/repl.rs

This PR moves network parsing to lib.rs and changes repl to return an error instead of defaulting to testnet if an invalid network name is given.

Add network parser function to lib.rs, remove network parsing from repl.rs

---

Cargo.toml
README.md
src/bdk_cli.rs
src/lib.rs

In this PR I add some missing metadata to Cargo.toml to prepare for publishing to crates.io. I also renamed the `repl.rs` bin to `bdk-cli` to be consistent with similar tools in other projects.  
See related PR to update the bitcoindevkit.org website docs to match updated `bdk-cli`.

Prep for publishing to crates.io, rename bin to bdkwallet

---

CHANGELOG.md
Cargo.toml
src/bdk_cli.rs
src/lib.rs

This PR upgrades BDK to version `0.3` and exposes some new features that can be used to use this library from wasm. This has been tested in our playground on bitcoindevkit/bitcoindevkit.org

Upgrade `bdk` and add a few more features for wasm

---

.github/workflows/cont_integration.yml
CHANGELOG.md
Cargo.toml
README.md
src/bdk_cli.rs
src/lib.rs

Depends on https://github.com/bitcoindevkit/bdk/pull/274
Added in Lib
- `CliOpts` struct and `CliSubCommand` enum representing top level cli options and commands
- `KeySubCommand` enum
- `handle_key_subcommand` function
Changed in Lib
- Renamed `WalletOpt` struct to `WalletOpts`
- `WalletSubCommand` enum split into `OfflineWalletSubCommand` and `OnlineWalletSubCommand`
- Split `handle_wallet_subcommand` into two functions, `handle_offline_wallet_subcommand` and `handle_online_wallet_subcommand`
- A wallet without a `Blockchain` is used when handling offline wallet sub-commands
Added in `bdk-cli`
- Top level commands "wallet", "key", and "repl"
- "key" command has sub-commands to "generate" and "restore" a master extended key
- "repl" command now has an "exit" sub-command, fixes #12 …

Re-organize wallet sub-commands and add `key` sub-commands

---

.github/workflows/cont_integration.yml

This PR sets the rust stable version in the CI pipeline to 1.50.0. This value will need to be updated manually when a new stable version of Rust :crab:  is released. Any clippy or other fixes required by a new stable version should be fixed in the same PR.

[ci] Manually set rust stable version in CI pipeline

---

CHANGELOG.md
Cargo.toml
src/lib.rs

This PR updates dependencies `bdk` to `0.4.0` and `bdk-macros` to `0.3.0` and adds a new `key` `derive` subcommand. The `key` `derive` sub-command derives an xpub from a given master xprv and derivation path.  
The purpose of the `derive` command is to make it easier to create xpubs for use in testing multisig descriptors. For example an xpub can be derived and stored in an environment variable like this:
```shell
echo \"$ALICE_XPRV\"
"tprv8ZgxMBicQKsPfQjJy8ge2cvBfDjLxJSkvNLVQiw7BQ5gTjKadG2rrcQB5zjcdaaUTz5EDNJaS77q4DzjqjogQBfMsaXFFNP3UqoBnwt2kyT"
export ALICE_XPUB=$(bdk-cli key derive --xprv $ALICE_XPRV --path "m/84'/1'/0'/0" | jq -r ".xpub" | sed 's/^\[.*\]//g')
echo \"$ALICE_XPUB\"
"tpubDDrcq8JNTLVwaGnXp7KqZZxFJoic49ikEotWnpm6hpMY2hL2F1hpgbBBkEdsFJHU1iAx9DzMUKYr5mrphBMoXxhsBPhnVdmaoSCaeh …
```

Add key sub-command to 'derive' xpub

---

Cargo.toml
src/lib.rs

This fixes various dependency/feature things that were bothering me when porting old code to using this. See each commit for explanation :)

Various dependency fixups

---

.github/workflows/cont_integration.yml
CHANGELOG.md
src/bdk_cli.rs
src/lib.rs

Closes issue #20 
Add to library `CliSubCommand::Compile` enum variant and `handle_compile_subcommand()` function.
Add to `bdk-cli` tool a new top level command "Compile" to compile a miniscript policy to an output descriptor.
Help output:
```
$ cargo run --features=repl,electrum,compiler help compile
...
bdk-cli-compile 0.2.1-dev
Miniscript policy compiler
USAGE:
bdk-cli compile [OPTIONS] <POLICY>
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
-t, --type <TYPE>    Sets the script type used to embed the compiled policy [default: wsh]  [possible values: sh,
wsh, sh-wsh]
ARGS:
<POLICY>    Sets the spending policy to compile
```
Example usage:
```
$ cargo run --features=repl,electrum,compiler compile --type sh-wsh …
```

Add 'compile' sub-command, minor cleanup

---

CHANGELOG.md
src/bdk_cli.rs

This removes some unwraps in favor of ? during handling of the commands.
During development I frequently hit ChecksumMismatch while changing the descriptor and keeping the same wallet name, I imagined users may be confused so I detailed the message.
On top of #22 
Error handling is a little nicer for end-user but it comes at the expense of losing stacktrace information in case of errors, so it may be controversial. However, we are now writing blog post and expanding user base so I think it is better.

Remove unwraps in bdk_cli and more detailed message for ChecksumMismatch

---

Cargo.toml

Preparing for next release with bump to latest `bdk` and `bdk-macros` versions plus fixing docs.rs build features.

Bump 'bdk' and 'bdk-macros' versions, fix docs.rs build features

---

src/lib.rs

Output:
```
{
"xprv": "tprv8ZgxMBicQKsPeCmJHoy1pwYwgTyWz2WG1W9MAuqwTFbj7AtiPVdy1C6oZJFMLMyZskVCXsf9XcG2mSVm9twaKkqhKXCh96fbuaPUxBz5Sr4/84'/1'/0'/*",
"xpub": "[33b0970f/84'/1'/0']tpubDCyioiPrh9dHkBdomkQhvTFeFnKec2XU9a3BM4Z9Y4vVXGWjMj9je3dcV7HjqN21PMH8M98ejEEQwoof8FE4JkD1jqKJhxFwJAxYtAgeieN/*"
}
```
I've been using the same format for xprv as xpub [fingerprint/hardened/path]xprv/*, not sure how to get the xprv in that format - or if it is required.

extended bdk-cli key derive to output xprv

---

.github/workflows/cont_integration.yml
CHANGELOG.md
Cargo.toml
README.md
src/bdk_cli.rs
src/lib.rs

This PR adds the compact filter configuration to connect bdk-cli with a Bitcoin Core node serving compact filters.
I have updated the Readme doc with new usage instruction. If thats not clear (because github doesn't show .md outputs in PR) below is the instruction:
To sync a wallet to Bitcoin Core node (assuming a regtest node at 127.0.0.1:18444) serving compact filters:
Then run:
```shell
cargo run --features compact_filters -- --network regtest wallet --node 127.0.0.1:18444 --descriptor "wpkh(tpubEBr4i6yk5nf5DAaJpsi9N2pPYBeJ7fZ5Z9rmN4977iYLCGco1VyjB9tvvuvYtfZzjD5A8igzgw3HeWeeKFmanHYqksqZXYXGsw5zjnj7KM9/*)" sync
```

Compact filter

---

.github/workflows/cont_integration.yml
CHANGELOG.md
Cargo.toml
src/lib.rs

Adapting to the current master branch of bdk.
After the next release of bdk, Cargo.toml, should go back to use crates.io

adapt to the changed signing interface in bdk 0.7

---

README.md

This PR adds an _Install bdk-cli_ section to the readme, which includes 2 parts: installing from source, and installing from crates.io.
This PR addresses the issue brought up in #29.

Add install instructions for crates.io

---

src/bdk_cli.rs
src/lib.rs

Added "wallet" flag `-v` or `--verbose` for the following offline wallet subcommands: "create_tx", "sign" and "finalize_psbt".
Passed `walletOpts` down to `handle_offline_sub_commands` so that the subcommands can access and know if the verbose flag was set in wallet level.
This PR addresses the issue brought up in #32.

Wallet Verbosity for PSBT details

---

src/lib.rs

This adds in verbosity for transactions in `list_transactions`. If verbosity was enabled, it shows the raw transaction as a human readable json.
```bash
❯ ./target/debug/bdk-cli wallet -v -d "wpkh([ece99850/1]tprv8dK67BQwyn6i3gDamn3s5ENnEbAg7DM4FACGygM3wXui4JAWQjUNzuiuNcTh57uFjGQAPrQq22VAxYTyGVnoQt3s4PmBeUHJtt7oJC7wXNk/*)" list_transactions
[
{
"fees": 141,
"height": null,
"received": 8859,
"sent": 10000,
"timestamp": 0,
"transaction": {
"input": [
{
"previous_output": "6fafe559892e085419596670415826098d85a39f5c707eb5db8cb3e87cab5bbb:1",
"script_sig": "",
"sequence": 4294967295,
"witness": [... redacted due to length ...]
}
],
"lock_time": 0,
"output": [
{
"script_pubkey": "001471526a6e2a88df813db190190130fdf27bcd6bb9",
"value": 8859
},
{
"script_pubkey": …
```

Show tx details in case verbose is enabled

---

.github/workflows/cont_integration.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
build.rs
src/bdk_cli.rs
src/lib.rs

Allow at most one blockchain client feature be enabled at a time for builds. If no blockchain client feature is enabled then online wallet commands are disabled. This will simplify the options shown to the user and make adding new blockchain clients (such as #36) easier. ~~Electrum is still the default, to make a build with a different blockchain client the `--no-default-features` build option will need to be used.~~ No blockchain client is included in the `default` features, so if one is needed it must be specified with `--features`.  I also added a default esplora server url so the user doesn't need to specify one if selecting that client, which is how the electrum and compact_filters clients work.
I changed the server option for both `electrum` and `esplora` to --server or -s since …

Allow enabling at most one blockchain client feature

---

.github/workflows/code_coverage.yml
.github/workflows/cont_integration.yml
Cargo.lock
Cargo.toml
src/bdk_cli.rs
src/lib.rs

This PR updates the upstream BDK version to latest release (`v0.10.0`). 
The latest release of BDK includes some breaking changes, some of which are handled here. A previously available function in BDK, `maintain_single_recipient()` is changed into `allow_shrinking()` which requires a scriptpubkey to be specified. So far I couldn't find any public API in BDK using which a scriptpubkey (or the transaction) can be retrieved from the wallet given a TxID. Marked the code with a `TODO`. It probably needs some additional API in BDK. Made an issue (https://github.com/bitcoindevkit/bdk/issues/427) to track this.
BDK `esplora` blockchain module has been divided into two types `using-ureq` and `using-reqwest`. `reqwest` is an async feature in BDK, which produces `Future` related errors in `bdk-cli` …

Update BDK version to 0.12.0

---

CHANGELOG.md
README.md
src/lib.rs

* Fix default esplora server URL to `https://blockstream.info/testnet/api` to match default `bdk-cli` network which is also `testnet`. 
* Update README instructions and examples with features `esplora-ureq` and `esplora-reqest`.
I think this is the simplest way to fix the esplora server URL to match the specified bitcoin network. If the user uses the option to change the bitcoin network then they should also expect to change the esplora (or other blockchain client) server url.

Small explora fixes

---

CHANGELOG.md
src/lib.rs

Replace `wallet bump_fee` command `--send_all` with new `--shrink ADDRESS` option to reduce the output amount for the  specified address to increase RBF transaction fee.
This new option is primarily needed when bumping the fee of a `send_all` transaction or any other transaction that doesn't have a change output that can be reduced to bump the fee on the new RBF transaction.
Steps I used to test
1. create wallet with two utxos 
2. create and broadcast send_all tx with rbf enabled and 1 sat/vbyte fee back to testnet faucet
3. create and broadcast bump_fee rbf for above tx with 7 sat/vbyte fee and shrinking the testnet faucet address
https://mempool.space/testnet/tx/e35892843875e084f39c5285ee6f522764210351f78cd89305a49efbf4bfea48

Replace `wallet bump_fee` command `--send_all` with new `--shrink` option

---

.github/workflows/cont_integration.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
src/bdk_cli.rs
src/lib.rs

adding the commands for proof-of-reserves using the separate repository

---

.github/workflows/code_coverage.yml

To match with existing codecov of BDK, Tarpaulin based codecov in bdk-cli is changed to grcov.

Update codecov to grcov from Tarpauline

---

.github/workflows/cont_integration.yml
src/lib.rs

There was an inconsistency in `rpc` tests. The `RpcOpts` was missing from the wallet struct. This wasn't caught before because we didn't have `rpc` tests in CI. Fixed that too.
Also removed redundant wallet options from feature gated tests.

[bug] Fix RPC tests

---

src/bdk_cli.rs
src/lib.rs

bdk-cli had lots of ugly unwraps through out the code. All the unwraps inside the library (except tests) were removed and errors were propagated with `bdk::Error` type.

Improve error handlings.

---

Cargo.lock
Cargo.toml

MSRV issue with fd-lock 3.0.1 was fixed with version 3.0.2. See: https://github.com/yoshuawuyts/fd-lock/issues/16
But now I had to limit the rustyline version to <9.1.0 because that version upgrades to [rust edition 2021](https://doc.rust-lang.org/edition-guide/rust-2021/index.html) which we haven't adopted yet and would change our MSRV to 1.56.0.

Un-pin fd-lock version

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/bdk_cli.rs
src/lib.rs

if no wallet name was provided, use one derived from the descriptor
Is there a better place to use wallet_name_from_descriptor so that the generated name shows up in the unit tests instead of the placeholder?

if no wallet name was provided, use one derived from the descriptor

---

Cargo.lock
Cargo.toml
src/lib.rs

This fixes the help docs for the `repl` and `wallet` subcommands. The `repl` subcommand was showing the proxy options docs instead, and the `wallet` subcommand was showing the description from the `WalletSubCommand` enum.
This is a workaround for `structopt` issue #333, #391, #418; see https://github.com/TeXitoi/structopt/issues/333#issuecomment-712265332
Before this PR this was showing:
```shell
$ cargo run --features esplora-ureq,compiler -- --help
...
SUBCOMMANDS:
compile    Compile a miniscript policy to an output descriptor
help       Prints this message or the help of the given subcommand(s)
key        Key management sub-commands
repl       Proxy Server options
wallet     Wallet sub-commands
```
After this PR we get:
```shell
$ cargo run --features esplora-ureq,compiler -- --help …
```

Fix repl and wallet help docs

---

CHANGELOG.md
src/bdk_cli.rs
src/lib.rs

Fixes https://github.com/bitcoindevkit/bdk-cli/issues/67
This PR adds an optional `cookie` arg to pass on cookie file if user needs to use that instead of basic user:password based authentication.
bitcoin core will only generate a `.cookie` file if rpc username passwords are not set in `bitcoin.conf`. Thus cookie file doesn't have a default. User should only provide it if they know a cookie file exists, or else "File not found" error is returned.

Add cookie authentication option for rpc

---

CHANGELOG.md
LICENSE
LICENSE-APACHE
LICENSE-MIT
src/bdk_cli.rs
src/lib.rs

Re-licensing repo to dual MIT and Apache 2.0 and updating project name to "Bitcoin Dev Kit".  I want to do this now before we get too many new contributors. Also because this project is being proposed for use in a commercial project so I want to clarify it is broadly licensed as is the rest of BDK. 
This issue is based on https://github.com/bitcoindevkit/bdk/issues/301. 
If you're on the below list and agree with this change please add a comment with "I hereby license my previous contributions to Bitcoin Dev Kit under Apache 2.0 and MIT licenses."

Re-licensing to dual MIT and Apache 2.0 and update project name

---

src/bdk_cli.rs

Because we didn't had `maybe_descriptor_wallet_name()` in repl, the following command would fail
```
$ ./target/debug/bdk-cli repl -d "wpkh([b8b575c2/84'/1'/0'/0]tprv8icWtRzy9CWgFxpGMLSdAeE4wWyz39XGc6SwykeTo13tYm14JkVVQAf7jz8WDDarCgNJrG3aEPJEqchDWeJdiaWpS3FwbLB9SzsN57V7qxB/*)"
thread 'main' panicked at 'We should always have a wallet name at this point', src/bdk_cli.rs:116:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

[bug fix] Add `maybe_descriptor_wallet_name()` in repl mode

---

.github/workflows/cont_integration.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
src/bdk_cli.rs
src/lib.rs

Fixes #81 
Also added `verify` feature flag which enables transaction verification against consensus rules during sync.
I also had to disable the `reserves` tests and that feature will be broken until we can get it updated to use `bdk` `0.17` also.  I created an issue https://github.com/weareseba/bdk-reserves/issues/4.

Update to bdk 0.17.0

---

.github/workflows/cont_integration.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
src/bdk_cli.rs

Fixes https://github.com/bitcoindevkit/bdk-cli/issues/55. I decided to go for one feature flag for each backends as they made dependency management easier. Because different backend will have different dependency, and we don't wanna have redundant ones. Also it makes the commands a little shorter.
Right now its not that useful because the backend APIs are not exposed. So I can't really do much other than sync/send in the command line. (unlike testnet we cannot send coins to bdk from outside of local regtest node). So to make it useful in repl mode as described in the issue, we also have to expose the blockchain apis in bdk-cli command in some way (at least the basic stuffs, address, send, generate). Looking for suggestions on this.
usage looks like this: 
```
cargo run --features …
```

Auto deploy regtest nodes in background

---

src/lib.rs

Fetch address index in verbose mode for get_new_address

---

Cargo.lock
src/lib.rs

Did a `cargo update` to update `miniscript` dependency in Cargo.lock to `6.1.0` and fix related audit issue. 
```text
Crate:         miniscript
Version:       6.0.1
Warning:       yanked
Dependency tree: 
miniscript 6.0.1
└── bdk 0.17.0
├── bdk-reserves 0.17.0
│   └── bdk-cli 0.5.0
└── bdk-cli 0.5.0
```
There is still one audit issue that I can't figure out how to fix, I created #85 to track it.

Update miniscript version to 6.1.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
build.rs
src/bdk_cli.rs

- Add distinct `key-value-db` and `sqlite-db` features, keep default as `key-value-db`
- Put cached wallet data in separate directories: `~/.bdk-bitcoin/<wallet_name>`
- Put compact filter data in `<wallet_name>/compact_filters`
- Depending on the db used put cached wallet data in: `<wallet_name>/wallet.sled/` or `<wallet_name>/wallet.sqlite`
This change will help test BDK with different databases, in particular for manually testing DB migrations such as in https://github.com/bitcoindevkit/bdk/pull/502.

Add key-value-db and sqlite-db features, separate wallet directories

---

src/bdk_cli.rs

I noticed that when I disable default features and don't enable the `repl` feature that the regex tests fail because they need the regex dependency that the `repl` feature brings in. This PR is to simply disable the regex related test code if the `repl` feature isn't enabled.

Disable regex tests when repl feature not enabled

---

.github/workflows/cont_integration.yml

Currently the way `ExternalReserves` functionality is written, it can only be used with `electrum` feature. The tests should fail if the implementation behavior is enforced.. Disabling the tests in CI.
Also removing the `regtest-esplora` features from the tests, because they won't work when #92 lands.

Remove some of the reserves and regtest features

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/handlers.rs
src/main.rs

We previously had the esplora-reqwest feature, but it would use
sync reqwest, as the "async-interface" feature in BDK wasn't set.
This commit sets this feature so that using `esplora-reqwest` always
uses async mode.

Use async with esplora-reqwest

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/commands.rs
src/utils.rs

- Update `bdk` and `bdk-reserves` to v0.22.0.
- Change rpc `--skip-blocks` option to `--start-time` which specifies time initial sync will start scanning from.
I  haven't verified the bits and bytes of the new `reserves` PSBT in the tests. I assume it's different for the same reason as the other tests in `bdk-reserves` when we switched to bdk 0.22, but I could use some help confirming that.
**This is draft until `bdk` and `bdk-reservers` v0.22 are published.**

Update bdk dependency to 0.22

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/commands.rs
src/handlers.rs
src/main.rs
src/nodes.rs
src/utils.rs
tests/integration.rs

fixes #62 
fixes #76 
On the name : 
If Bitcoin wallet devs had to have a "calculator", this is what it might look like. One single interface to do all wallet and node operations.  
This PR does the following
- Update electrsd to latest version. We need this to use it for out auto deployed backends.
- Add the remaining codes to `nodes.rs` module to define basic node operation apis on the `Nodes` enum.
- Add a new `node` command in ` CliSubCommand` which has its own subcommand `NodeSubCommand`, These subcommands are essentially `bitcoin-cli` calls. And only the basic ones are included so far. We can also compose multiple `bitcoin-cli` calls to create our own commands in future.
- Update the `handlers` to handle newly added `NodeSubCommands`.
- Update in `utils` : 
- This includes handling …

Satoshi's Calculator.

---

CHANGELOG.md
README.md
src/commands.rs
src/handlers.rs
src/main.rs
src/nodes.rs
src/utils.rs

After #99 the previous documentation have been removed and new docs as per `structopts` documentation. This PR adds more documentation across the crate.. 
This PR is above #102 , to accommodate all the further refactoring changes. 
The Readme About section have been updated with more details.. Readme format made aligned with the BDK project itself..
The Readme file is used itself as the crate level documentation in docs.rs too..

Update crate documentation

---

src/commands.rs
src/handlers.rs

This enables users to send an arbitrary string message through a txn-output. The maximum size of this string-literal can be length of 80-bytes.

Add add_data enables op_return for bdk-cli

---

src/utils.rs

Making sure to create the wallet dir only when necessary (database is either sqlite or key-value)

Create wallet dir only when necessary

---

.github/workflows/cont_integration.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
src/commands.rs
src/main.rs
src/wasm.rs

This PR adds a module to bdk-cli that exposes some structures/functions to WASM. You can see it in use here: https://github.com/bitcoindevkit/bitcoindevkit.org/pull/118
Based on #116

Update bdk cli for wasm

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Bump version and update changelog file for version 0.6.0. Also updated Cargo.lock. 
Once this is ACK'd I'll  publish the repo to crates.io.

Bump version to 0.6.0

---

.github/workflows/cont_integration.yml
Cargo.lock
Cargo.toml
src/commands.rs
src/handlers.rs
src/main.rs
src/wasm.rs

Fixes #113.
This is an attempt to migrate from `structopt` to `clap v0.3` which provides very similar kind of derives as `structopt`. Changes are straight forward. But this comes with few more problems. 
- with clap `v3.2.22` the MSRV pushes up to `1.57.0`.. The last clap of MSRV `1.56.0` was `clap 3.2.5`.. But even that doesn't seem to be working at MSRV `1.56.0` anymore, as bunch of underlying lib has upgraded. 
- `clap v3.0` doesn't seem to support custom vector parsing well, reported here https://github.com/clap-rs/clap/issues/1704. This is required for `recipient` parsing which is a `Vec<(Script, u32)>`.  Workaround for that is to use vecs of strings and parse them at runtime in `create_tx` handler. Included in the PR.    
`structopt` is currently freezed at `clap 2.0` and doesn't …

Migrate from structopt to clap.

---

.github/workflows/code_coverage.yml
.github/workflows/cont_integration.yml
Cargo.lock
Cargo.toml

Fixes #112
Removes compact block filters temporarily.

Remove cbf

---

README.md

Remove mention of compact_filters from README until it can be re-enabled
I didn't notice this before I merged #125.

Remove mention of compact_filters from README until it can be re-enabled

---

src/handlers.rs

Fixes #97
Add a finalizer check before broadcasting psbts.

Check if psbt is final, before broadcasting

---

Cargo.lock
Cargo.toml
src/utils.rs

Update to bdk v0.26.0

---

Cargo.lock
Cargo.toml

As we are already at msrv 1.57.0, so we can bump electrsd to v0.22.
Which fixes #85 and potentially #131  too.. 
Bump `electrsd` version to `v0.22.*`.

update electrsd to v0.22.*

---

.github/workflows/cont_integration.yml
src/commands.rs
src/handlers.rs

As BDK bumped its stable to 1.65, it is safe for us to move it up also.  
`1.65` cause clippy warning that `Eq` isn't derived while `PartialEq` is derived for the commands. We can't derive `Eq` for commands, as there is a `fee_rate` which is `f32` which isn't `Eq`, and this effect cascades to all structures. We also need `PartialEq` for the tests.
A few options were:
- allow the clippy warning conditionally for `1.65`, `1.57` doesn't have that lint. The way to do that is by creating custom features for different versions and making a build script that activates specific features for specific versions. Feature gate the clippy lint. or use https://github.com/dtolnay/rustversion which is an extra dep.
- Remove `PartialEq` and create a method on `CliOpts` to translate it into `Vec<String>`, …

bump stable rustc version to 1.65

---

Cargo.lock
Cargo.toml
src/handlers.rs

Upgrades to bdk `v0.27.0-rc.1`. Pins dependency `zip` to `v0.6`, as latest version of `zip` moved up their MSRV to `1.59`. 
of the PR were done in a specific way -->
- BDK version bumped to `0.27`.

Bump bdk to `v0.27.0`

---

Cargo.lock
Cargo.toml

Update `bdk` from 0.27 to 0.27.1 to fix bitcoindevkit/bdk#866.
Once we get this verified for `bdk-cli` and `bdk-ffi` I'll publish the new bdk release and update this PR to use the new version.
Changed
- Update bdk from 0.27 to 0.27.1 to fix bitcoindevkit/bdk#866.

Update bdk from 0.27 to 0.27.1

---

Cargo.lock
Cargo.toml
src/commands.rs
src/handlers.rs
src/utils.rs

Adding hardware signers, so that hardware wallets can be used to sign transactions.
~~It doesn't work 100% yet for me. 
I am using the following wallet: 
https://github.com/RCasatta/electrum2descriptors/blob/main/tests/wallets2descriptors.rs#L89
https://github.com/RCasatta/electrum2descriptors/blob/main/tests/wallets/multisig_hw_segwit
I can create and sign a transaction with this version of bdk-cli. It displays the details on the Trezor and everything looks good so far. But in the CLI output of bdk-cli it says  "is_finalized= false" and when I open the supposedly signed tx in Electrum, it aslo says "Status: Unsigned". 
So, something must still be missing.~~
Initially I had some dependency problems, so I deleted Cargo.lock. That solved the dependency problems, but that's the reason for …

adding hardware signers

---

.github/workflows/cont_integration.yml
Cargo.lock
README.md

To build with MSRV 1.57.0:
- pin tokio to 1.29.1
- pin any version of tempfile to 3.6.0
- pin cc to 1.0.81
- pin flate2 to 1.0.26
None.

ci: pin tokio to 1.29.1 to build with MSRV 1.57.0

---

src/handlers.rs
src/utils.rs

This PR set the data directory for the Kyoto client. See [comment](https://github.com/bitcoindevkit/bdk-cli/pull/181#issuecomment-2863853425)
This PR ensures that the `light_client_data` directory created by the Kyoto client is in the wallet's data directory.

chore(cbf): set kyoto client data dir

---

src/commands.rs
src/error.rs
src/handlers.rs
src/utils.rs

The actual implementation comes down to listening for an info message that reports the transaction was sent to a peer. For simplicity I am ignoring any wallet updates, but if the user calls the `Sync` command they can catch them. Follows up #181

Implement transaction broadcasting for Kyoto

---

.github/workflows/code_coverage.yml
tests/integration.rs

The code coverage workflow broke and this change fixes it.
This is copy/pasted from the bdk repo job of the same name.

ci: fix code coverage workflow

---

README.md

Update README rust version badge to 1.75.0.
I forgot to do this on the last release.

chore: update README rust version badge to 1.75.0

---

Justfile
README.md

This PR adds Justfile config file for the just command runner.
The default values for `datadir`, `rpcuser` and `rpcpassword` set in the Justfile are those used in the project.

Add Justfile command runner

---

src/handlers.rs

Kyoto now holds on to a transaction internally until it is successfully broadcast, so we can broadcast the transaction immediately once the node starts up, and wait for a confirmation or 30 second timeout
Successful test on Signet. Note that `Testnet4` still has the difficulty adjustment bug when loading block headers from storage.

Kyoto: Remove connection requirement to send tx

---

CHANGELOG.md
Cargo.lock
Cargo.toml

This PR bump version to 2.0.0
Fixes #215

Bump version to 2.0.0
